language: ruby
rvm:
  - 2.4.2
before_script:
  - rm config/database.yml
  - mv config/travis.database.yml config/database.yml
  - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
before_install:
  - mysql -e 'CREATE DATABASE inabox_test;'
script:
  - bundle exec rake db:test:prepare
  - bundle exec rspec
services:
  - mysql
  - redis-server
